# Generated by Django 3.1.3 on 2021-04-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210407_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['flatNo']},
        ),
    ]
